# Generated by Django 6.0.3 on 2026-03-14 15:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL)),
                ('election_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='elections.electionstatus')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='elections.electiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('eligible_voters_count', models.IntegerField(default=0)),
                ('voters_count', models.IntegerField(default=0)),
                ('turnout_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_final', models.BooleanField(default=False)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='elections.election')),
                ('generated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('results_publish_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_units', to='elections.organizationalunit')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='elections.organizationalunit'),
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('student_or_employee_no', models.CharField(max_length=50, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='elections.organizationalunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
                ('avatar_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_avatars', to='elections.storedfile')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RESULT_PDF', 'Result PDF'), ('SUMMARY_PDF', 'Summary PDF'), ('PROTOCOL_PDF', 'Protocol PDF')], max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='elections.election')),
                ('election_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='elections.electionresult')),
                ('generated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='elections.storedfile')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.IntegerField()),
                ('campaign_description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='elections.person')),
                ('avatar_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_avatars', to='elections.storedfile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('AVATAR', 'Avatar'), ('PROGRAM', 'Program'), ('POSTER', 'Poster'), ('OTHER', 'Other')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('election_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='elections.electioncandidate')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_attachments', to='elections.storedfile')),
            ],
        ),
        migrations.CreateModel(
            name='VotingEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_status', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending')], default='GRANTED', max_length=30)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='elections.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_eligibilities', to='elections.person')),
            ],
        ),
        migrations.CreateModel(
            name='VotingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_choices', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_choices', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_blank_vote', models.BooleanField(default=False)),
                ('allow_vote_change', models.BooleanField(default=False)),
                ('requires_turnout_threshold', models.BooleanField(default=False)),
                ('turnout_threshold_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_rule', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='VotingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.CharField(max_length=120, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_tokens', to='elections.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_tokens', to='elections.person')),
            ],
        ),
        migrations.CreateModel(
            name='VotingParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='elections.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_participations', to='elections.person')),
                ('voting_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='elections.votingtoken')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_key', models.CharField(max_length=120, unique=True)),
                ('ballot_status', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.election')),
                ('voting_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ballot', to='elections.votingtoken')),
            ],
        ),
        migrations.CreateModel(
            name='BallotSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='elections.ballot')),
                ('election_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_selections', to='elections.electioncandidate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ballot', 'election_candidate'), name='unique_candidate_per_ballot'), models.UniqueConstraint(fields=('ballot', 'selection_order'), name='unique_selection_order_per_ballot')],
            },
        ),
        migrations.CreateModel(
            name='ElectionResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_count', models.IntegerField(default=0)),
                ('votes_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ranking_position', models.IntegerField()),
                ('election_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_items', to='elections.electioncandidate')),
                ('election_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='elections.electionresult')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election_result', 'election_candidate'), name='unique_result_item_per_candidate'), models.UniqueConstraint(fields=('election_result', 'ranking_position'), name='unique_ranking_position_per_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='electioncandidate',
            constraint=models.UniqueConstraint(fields=('election', 'person'), name='unique_candidate_per_election'),
        ),
        migrations.AddConstraint(
            model_name='electioncandidate',
            constraint=models.UniqueConstraint(fields=('election', 'candidate_number'), name='unique_candidate_number_per_election'),
        ),
        migrations.AddConstraint(
            model_name='votingeligibility',
            constraint=models.UniqueConstraint(fields=('election', 'person'), name='unique_eligibility_per_person_and_election'),
        ),
        migrations.AddConstraint(
            model_name='votingtoken',
            constraint=models.UniqueConstraint(fields=('election', 'person'), name='unique_token_per_person_and_election'),
        ),
        migrations.AddConstraint(
            model_name='votingparticipation',
            constraint=models.UniqueConstraint(fields=('election', 'person'), name='unique_participation_per_person_and_election'),
        ),
    ]
