# Generated by Django 6.0.3 on 2026-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auditlog_electionevent_notification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='electionevent',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='election_event_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='electionschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='election_schedule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='votingrule',
            constraint=models.CheckConstraint(condition=models.Q(('max_choices__gte', models.F('min_choices'))), name='voting_rule_max_choices_gte_min_choices'),
        ),
        migrations.AddConstraint(
            model_name='votingrule',
            constraint=models.CheckConstraint(condition=models.Q(('requires_turnout_threshold', True), ('turnout_threshold_percent__isnull', True), _connector='OR'), name='voting_rule_threshold_required_or_null'),
        ),
    ]
